### ISSUE TITLE
Unable to use facebook login with Android binding. 

### ISSUE THREAD

**Issue by kmikhai** [ianlevesque/gigya-sdk-xamarin#2]
For iOS works ok. For Android, get the dreaded 

{ errorCode:400006
errorMessage:
Login with Facebook is supported only using Facebook SDK native login.
errorDetails:null
data:{"provider":"facebook”}}

In response to the login shown below.
            var tcs = new TaskCompletionSource<GSResponse>();

```
        var p = new GSObject();
        p.Put("provider", GigyaUtils.ProviderToString(provider));

        var responseListner = new ResponseListner(tcs);

        //GSAPI.Instance.ShowLoginUI(p, new Listen(), null);

        GSAPI.Instance.Login(p, responseListner, false, null);

        return tcs.Task;
```

Which is indicative of I think Gigya SDK not detecting the facebook SDK even though it's included.

Based on research of comparable native Gigya SDK for Android, it seems that the issue may be that the native SDK uses Facebook SDK as an .aar file (library resource) vs Facebook SDK being bound as a .jar in the binding provided with this project.

Have you experienced that issue by chance? Do you think there's merit to the .aar theory, and do you think it's possible to do a gigya SDK Xamarin binding with Facebook SDK as .aar?

**Comment by ianlevesque** [comment]
We're currently using this successfully in an application. You need to install the Xamarin.Facebook component alongside this binding, version 3.22 specifically. Gigya does not yet support newer versions.

**Comment by kmikhai** [comment]
Thank you very much! That got us through it.

**Comment by xamarinnerd** [comment]
@kmikhai @ianlevesque Do you have a working sample of the Gigya integrated app?
